### ISSUE TITLE
interface runs in dock and bar

### ISSUE THREAD

**Issue by anamorph** [picaso/parrot-zik-status#1]
Iterface seems to run in dock and bar, not bar only.

**Comment by picaso** [comment]
@anamorph I will address that in the upcoming release. I just saw this now, have no idea why i got no notification

**Comment by picaso** [comment]
[#bbfb094 ](https://github.com/picaso/parrot-zik-status/commit/bbfb094c66ad7b6b2de1e60374d3c78278dbe0d0)

**Comment by picaso** [comment]
@anamorph a new update has been pushed out to address this issue: http://picaso.github.io/parrot-zik-status/

## Feature enhancements

https://github.com/picaso/parrot-zik-status/releases/tag/v0.23-alpha

Please can you help test that everything works? Thanks.

**Comment by anamorph** [comment]
fixed ! Thanks !!!
