### ISSUE TITLE
Parrot Status crashes on start (Sierra)

### ISSUE THREAD

**Issue by visualmethod** [picaso/parrot-zik-status#10]
The app is crashing in an non-Retina iMac 27" (2012) running macOS 10.12. It doesn't open even with all the GateKeeper safeties off.

I've attached the latest crash and log reports to the issue, just tell me if you need something else.
[ParrotStatus_2016-10-01-122909.txt](https://github.com/picaso/parrot-zik-status/files/504268/ParrotStatus_2016-10-01-122909.txt) 
[systemlog.txt](https://github.com/picaso/parrot-zik-status/files/504269/systemlog.txt)
[diagnosysdata.txt](https://github.com/picaso/parrot-zik-status/files/504270/diagnosysdata.txt)
[processlog.txt](https://github.com/picaso/parrot-zik-status/files/504271/processlog.txt)

Thanks and regards,

**Comment by shams-ahmed** [comment]
@visualmethod i think the latest changes in master resolve unwrapping issue. any chance you can build and give it a go?

**Comment by visualmethod** [comment]
@shams-ahmed thanks for the indications. I've tried to build using the script but it seems there's a dependency error after installing the pods (probably my fault, since it's my first time compiling a Swift app)

Any idea when the next release should be ready?

**Comment by picaso** [comment]
I think that is because sierra is using swift 3 and the app is in swift 2. I just ordered a new mac, and once it arrives I will be moving the app over to swift 3. @shams-ahmed Can you give me the binary for your built version so i can put it up? Thanks.

**Comment by shams-ahmed** [comment]
@picaso i've got a working version on another computer which i won't have access till Monday. ive got a branch for [swift3](https://github.com/shams-ahmed/parrot-zik-status/tree/swift3). It builds but having issue display the app on the status bar.

p.s using Sierra with swift 2 shouldn't cause a issue doing the same actually, only time it causes is when there a weird issue with the headphone but there odd edge cases

**Comment by picaso** [comment]
@shams-ahmed awesome. I will take a look and try to make it work.

**Comment by shams-ahmed** [comment]
[ParrotStatus.zip](https://github.com/picaso/parrot-zik-status/files/561497/ParrotStatus.zip)
following builds works macOS Sierra

**Comment by picaso** [comment]
Updated to swift 3.0 thanks to @shams-ahmed for showing the way. I just got my new laptop, so development is back on. Unfortunately I can't get it to startup on my laptop, I will look into that.

**Comment by picaso** [comment]
Latest version fixes this issue. Pending publishing the zip.
