### ISSUE TITLE
Disconnected, but headphone connected

### ISSUE THREAD

**Issue by zijam** [picaso/parrot-zik-status#11]
I'm running masOS Sierra 10.12.1, my Zik 1 headphone is connected to my mac, but ParrotStatus said it is disconnected

![screen shot 2016-10-31 at 11 00 57](https://cloud.githubusercontent.com/assets/695088/19850606/9724e1f4-9f59-11e6-80c8-29ffb9d30354.png)

My Zik 1 headphone is running firmware version 1.10.0.

**Comment by picaso** [comment]
I do not support Zik 1 at the moment. Just Zik 2 and Zik 3. Zik one has a limited options and I do not have a zik 1 to test with. Sorry.
