### ISSUE TITLE
Issue with airplane mode on zik 3

### ISSUE THREAD

**Issue by TheLucidKid** [picaso/parrot-zik-status#12]
Hi there,
I've installed this tool on my mac, and turned on the airplane mode.
Since then I can't turn off the airplane mode, the bluetooth is not working anymore, and headphone is not detected by my smartphone and my mac (even when connected by cable).
Any idea about what's happening ?
Thanks

**Comment by picaso** [comment]
On your smartphone, try switching on and off the airplane mode, hopefully, that should fix it; Also, try turning the headphones off and on (or take out the batteries)
