### ISSUE TITLE
Button to connect/disconnect the headphone

### ISSUE THREAD

**Issue by jaumard** [picaso/parrot-zik-status#7]
It can be useful to manage this functionality :) instead of going into BT -> Parrot -> disconnect/connect it will be quicker.

I'm thinking of a button in the status bar that will connect the headphone if it's not and disconnect it if it's connected.

**Comment by picaso** [comment]
@jaumard good idea, but out of the scope of my original intention. Doesn't mean i am not open to seeing it implemented. I just won't prioritize it.
